//! Report I/O: write Markdown / JSON outputs and read the baseline.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

#[derive(Debug, Serialize, Deserialize)]
pub struct Snapshot {
    pub counts: BTreeMap<String, u64>,
}

/// Write `reports/debt/latest.{json,md}`. The directory is created as
/// needed and the files are overwritten.
///
/// # Errors
///
/// Returns an error if creating the directory or writing the files fails.
pub fn write_reports(root: &Path, counts: &BTreeMap<String, u64>) -> Result<()> {
    let dir = root.join("reports/debt");
    fs::create_dir_all(&dir).context("create reports/debt dir")?;

    let json = serde_json::to_string_pretty(&Snapshot {
        counts: counts.clone(),
    })?;
    fs::write(dir.join("latest.json"), json + "\n")?;

    let mut md = String::new();
    md.push_str("# debt-scan latest\n\n");
    md.push_str("Generated by `cargo run -p debt-scan -- scan`. Overwritten\n");
    md.push_str("on every run; not committed.\n\n");
    md.push_str("| Category | Count |\n");
    md.push_str("|---|---:|\n");
    for (k, v) in counts {
        // writeln! into a String can only fail on OOM; ignore the result.
        let _ = writeln!(md, "| {k} | {v} |");
    }
    fs::write(dir.join("latest.md"), md)?;

    Ok(())
}

/// Read `docs/debt/baseline.json` into a category -> count map.
///
/// # Errors
///
/// Returns an error if the file can't be read or doesn't parse as JSON.
pub fn read_baseline(path: &Path) -> Result<BTreeMap<String, u64>> {
    let text =
        fs::read_to_string(path).with_context(|| format!("read baseline at {}", path.display()))?;
    let snapshot: Snapshot = serde_json::from_str(&text)
        .with_context(|| format!("parse baseline at {}", path.display()))?;
    Ok(snapshot.counts)
}

/// Overwrite the baseline file with the given counts.
///
/// # Errors
///
/// Returns an error if creating the directory or writing the file fails.
pub fn write_baseline(path: &Path, counts: &BTreeMap<String, u64>) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let json = serde_json::to_string_pretty(&Snapshot {
        counts: counts.clone(),
    })?;
    fs::write(path, json + "\n")?;
    Ok(())
}

/// Signed difference per category: current - baseline.
#[must_use]
pub fn diff(
    baseline: &BTreeMap<String, u64>,
    current: &BTreeMap<String, u64>,
) -> BTreeMap<String, i64> {
    let mut out: BTreeMap<String, i64> = BTreeMap::new();
    for (k, v) in current {
        #[allow(clippy::cast_possible_wrap)]
        let cur = *v as i64;
        #[allow(clippy::cast_possible_wrap)]
        let base = *baseline.get(k).unwrap_or(&0) as i64;
        out.insert(k.clone(), cur - base);
    }
    out
}
